---
title: "v2"
author: "Maiko Hata"
format: 
  pdf:
    mainfont: "Times New Roman"
    sansfont: "Times New Roman"
fig-width: 6
fig-height: 4
csl: apa.csl
execute: 
  eval: true 
  echo: false
  message: false 
  warning: false
editor: visual
engine: knitr
---

```{r}
library(tidyverse)
library(here)
library(rio)
library(knitr)
library(gt)
library(DT)
library(reactable)
library(gtsummary)
library(kableExtra)
library(tinytex)
library(janitor)
library(tidylog)
library(sjPlot)
library(lme4)
library(tibble)
library(dplyr)
library(epitools)
library(readxl)
library(pwr)
library(rcompanion)
library(grateful)
library(distill)
library(readxl)
library(scales)
library(tidyr)
```

A. Table of 10 exit reasons

```{r Table of 10 exit reasons }
exit_categories <- import(here("Data","exit_categories.xlsx")) %>%
 clean_names() 
```

```{r}
kable(exit_categories, 
      caption = "Table of Exit Reasons",
      col.names = c('Exit Reasons','Exit Category Codes')) %>% 
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

B. National and Oregon CHILD COUNTS

NOTE TO SELF: ADD THE CENSUS NUMBER FOR FINAL PROJECT! BIND_ROWS!! WEEK 2? 3? Labs.

B-1. Load data

```{r}
#|label: load-OSEP-CHILDCOUNT-1920-data
# Imported excel file with multiple pages but specified only the second sheet. Yay 

childcount1920 <- read_excel("/Users/hata/Desktop/EDLD652_Diss/Data/1920-cchildcountandsettings-11.xlsx", sheet = 2)
```

```{r}
#|label: load-OSEP-CHILDCOUNT-1920-clean_names()
# Decided against clean_names as it messed up the column names 
# childcount1920 <- clean_names(childcount1920)
```

```{r}
# unique(childcount1920$state)
```

```{r}
#|label: load-OSEP-CHILDCOUNT-1920-filter_US_OR

childcount1920USOR <- childcount1920 %>% 
  filter(State %in% c("US and Outlying Areas", "Oregon"))
```

```{r}
#deleting the "total 100%" column because it messes up with the visualization 

childcount1920USOR <- childcount1920 %>%
  filter(State %in% c("US and Outlying Areas", "Oregon")) %>%
  select(-`Race/ethnicity Total3 (%)`)
```

B-2: chart 1

```{r}
#|label: Make_a_visualizaion_CHILDCOUNT-1920-US_OR 
```

```{r}
childcount1920USOR <- childcount1920USOR %>% 
  mutate_if(is.numeric, ~ round(.x, 2)) 
```

```{r}
kable(childcount1920USOR, 
      caption = "Child Count (US \\& Oregon)") %>% 
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

B-2: visualization 1

```{r}
# making it longer yeah
childcount1920USOR_long <- childcount1920USOR %>%
 gather(key = "race", value = "percent", -State)
```

```{r}
# Had to check to see why it wouldn't round up. Changed charactor to numeric 
str(childcount1920USOR_long$percent)
childcount1920USOR_long$percent <- as.numeric(childcount1920USOR_long$percent)
```

```{r}
# rounding up to 2 digits below the dicimal points 
childcount1920USOR_long <- childcount1920USOR_long %>%
  mutate(percent = round(percent, 2))
```

```{r}
# Chart 1 without viridis_d 
ggplot(childcount1920USOR_long, aes(x = State, y = percent, fill = race)) +
  geom_bar(stat = "identity") + 
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(title = "Percentage of Child Count by Race in US & Oregon",
       x = "State",
       y = "Percentage",
       fill = "Race") +
  theme_minimal() 
```

```{r}
# v.1 with viridis_d 
ggplot(childcount1920USOR_long, aes(x = State, y = percent, fill = race)) +
  geom_bar(stat = "identity") + 
  scale_fill_viridis_d() +  
  scale_y_continuous(labels = percent_format(scale = 1)) +
  labs(title = "Percentage of Child Count by Race in US & Oregon",
       x = "State",
       y = "Percentage",
       fill = "Race") +
  theme_minimal()
```

```{r}
# Change it to the bar chart 
ggplot(childcount1920USOR_long, aes(x = State, y = percent, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +  # "dodge" makes it a grouped bar chart
  scale_fill_viridis_d() +  # Apply Viridis discrete color palette
  scale_y_continuous(labels = percent_format(scale = 1)) +  # Format y-axis as percentages
  labs(title = "Percentage of Child Count by Race in US & Oregon",
       x = "State",
       y = "Percentage",
       fill = "Race") +
  theme_minimal() 
```

C. National and Oregon EXIT data by RACE

```{r}
#|label: load-OSEP-EXIT-data
# importing the data and cleaning it up: 
# This is the year 2013-2022. 
# 1. REMOVED DECEASED and NOT IN USE IN OREGON CATEGORY
# 2. CREATED THE complete_or_not_eligible combining three categories 

byrace <- import(here("Data", "race v.2.xlsx")) %>% 
  clean_names() %>% 
  select(-7, -12) %>% 
  mutate(complete_or_not_eligible = complete_prior_to_reaching_max_age_for_part_c + not_eligible_for_part_b_exit_with_no_referrals + not_eligible_for_part_b_exit_with_referrals_to_other_programs)
```

```{r}
#| label: aggregated-by-race
agg_by_race_and_state <- byrace %>% 
  group_by(race, area) %>% 
  summarize(exit_total = sum(exiting_total2), 
            withdrawal_by_parent = sum(withdrawal_by_parent),
            attempts_to_contact_unsuccessful = sum(attempts_to_contact_unsuccessful),
            moved_out_of_state = sum(moved_out_of_state),
            part_b_eligible_exiting_part_c = sum(part_b_eligible_exiting_part_c),
            complete_or_not_eligible = sum(complete_or_not_eligible))
```

```{r}
# aggregated by race for OR
race_oregon <- agg_by_race_and_state %>%
  filter(area == "Oregon")
```

```{r}
# aggregated by race for US
race_us <- agg_by_race_and_state %>% 
  filter(area == "US and Outlying Areas") 
```

```{r}
race_us <- race_us %>% 
  select(-area)
```

```{r}
# renaming category names to full names for race_us 
race_us <- race_us %>%
  mutate(race = recode(race,
    "AM" = "Alaska Native or American Indian",
    "AS" = "Asian",
    "BL" = "Black or African American",
    "HI" = "Hispanic/Latino",
    "WH" = "White",
    "MU" = "Two or More Races",
    "PI" = "Pacific Islander"
  ))

```

```{r}
# rename exit category names 
```

```{r}
# Made it LONGER for real! 
us_data_long <- race_us %>% 
  pivot_longer(
    cols = 3:7, 
    values_to = "values",
    names_to = "names"
  ) %>% 
  group_by(race) %>% 
  mutate(percentage = round(values/exit_total, digits = 4))
```

```{r}
# made it WIDER
us_data_wide <- us_data_long %>% 
  select(-c(exit_total,values)) %>% 
  pivot_wider(
    names_from = names,
    values_from = percentage
  ) 
```

OH NO where did Part B eligibility not determined go?!?!?

```{r}
# Changing category names in us_data_wide to clearner names 
us_data_wide <- us_data_wide %>% 
  rename(
    "Withdrawal by Parents" = withdrawal_by_parent, 
    "Disqualified" = attempts_to_contact_unsuccessful, 
    "Moved Out of State" = moved_out_of_state, 
    "Part B Eligible" = part_b_eligible_exiting_part_c, 
    "Complete or Not Eligible" = complete_or_not_eligible
  )
```

C. Oregon data by LANGUAGES

```{r}
# importing the data and clinining up: 
# 1. REMOVED DECEASED 
# 2. CREATED THE complete_or_not_eligible combining three categories 

bylang <- import(here("Data", "ODE data v2.xlsx")) %>% 
  clean_names() %>% 
  select(-6) %>%
  mutate(complete_or_not_eligible = no_longer_eligible_for_part_c_prior_to_reaching_age_three + not_eligible_for_part_b_exit_with_no_referrals +
not_eligible_for_part_b_exit_with_referrals_to_other_programs)

view(bylang)
```

```{r}
agg_by_lang <- bylang %>% 
  group_by(primary_language) %>% 
  summarize(exit_total = sum(total), 
            withdrawal_by_parent = sum(withdrawal_by_parent), 
            attempts_to_contact_unsuccessful = sum(attempts_to_contact_unsuccessful),
            moved_out_of_state = sum(moved_out_of_state),
            part_b_eligible_exiting_part_c = sum(part_b_eligible_exiting_part_c),
            complete_or_not_eligible = sum(complete_or_not_eligible))

# FROM v1: 
# aggregated by race for OR
#race_oregon <- agg_by_race_and_state %>%
 # filter(area == "Oregon")

# aggregated by race for US
#race_us <- agg_by_race_and_state %>% 
 # filter(area == "US and Outlying Areas")
```

```{r agg_by_lang_no_SL  take out Sign Language and NA rows}

agg_by_lang_no_SL <- agg_by_lang %>% 
  filter(primary_language != "Sign languages")
```

```{r}
kable(agg_by_lang, 
      caption = "Initial Oregon Data by Home Languages") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
